<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="VIBHJAIN-G2C5W" ignored="0" name="Test" tests="4" failures="2" timestamp="24 Feb 2018 04:38:53 GMT" time="0.076" errors="0">
  <testcase name="Test1" time="0.014" classname="com.cisco.automation.modules.fault.TestFault"/>
  <testcase name="TestHardAssertion" time="0.004" classname="com.cisco.automation.modules.inv.TestInv">
    <failure type="java.lang.AssertionError" message="expected [10] but found [11]">
      <![CDATA[java.lang.AssertionError: expected [10] but found [11]
	at com.cisco.automation.modules.inv.TestInv.TestHardAssertion(TestInv.java:35)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- TestHardAssertion -->
  <testcase name="TestSoftAssertion" time="0.007" classname="com.cisco.automation.modules.inv.TestInv">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [11] but found [10]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [11] but found [10]
	at com.cisco.automation.modules.inv.TestInv.TestSoftAssertion(TestInv.java:26)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- TestSoftAssertion -->
  <testcase name="Test1" time="0.001" classname="com.cisco.automation.modules.session_mon.TestSessionMon"/>
</testsuite> <!-- Test -->
